### ISSUE TITLE
Support list of embeds

### ISSUE THREAD

**Issue by justuscook** [foxbot/Discord.Addons.Paginator#8]
Would be cool if we could build an embed for each page.  Then we create embeds with images, multiple fields etc.

**Comment by SubZero0** [comment]
Would be possible with #7 ^^
(I was thinking if changing the Title and the Footer would be a nice addition)

**Comment by justuscook** [comment]
I see now, sorry, doh!

**Comment by SubZero0** [comment]
Don't close, that doesn't mean he will accept the PR.

**Comment by justuscook** [comment]
GitHub noob here, ;)

**Comment by justuscook** [comment]
@SubZero0 Looks like he accepted ur PR.  Once its on nuget  I can close this right?

**Comment by SubZero0** [comment]
If it solve your issue, yes (and it probably does).
